### PR TITLE
Upgrade to v0.60.0 of the Yandex Cloud Terraform Provider

### LINKED ISSUE #9: Upgrade to v0.60.0 of the Yandex Cloud Terraform Provider

### LINKED ISSUE #11: Upgrade to v0.61.0 of the Yandex Cloud Terraform Provider

### PR DESCRIPTION
**Pull request by stack72**
Fixes: #9﻿
Fixes: #11

### CODE REVIEW

**Comment by rauanmayemir** [comment]
Could this be merged in?
I've been waiting for this to deploy managed elasticsearch from pulumi.

**Comment by rauanmayemir** [comment]
Or maybe skip this one and go straight to v0.61.0? 😄

**Review by mikhailshilkov — APPROVED** [review]
LGTM. Do we need to changelog the breaking changes?

**Comment by stack72** [comment]
> LGTM. Do we need to changelog the breaking changes?

So I am going to say we don't need to as they believe this is a bug fix upstream to something that never worked but I guess we will see if we get a complaint about it 🤷‍♂️

**Pull request merged**
